
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/studyPlace
    username: sa
    password:

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    root: debug
    org.hibernate.SQL: debug # logger 에서 출력
    org.hibernate.type: trace # parameter(? 로 표시) 부분을 확인 할 수 있음